theme: jekyll-theme-minimal
title: Gustavo Cândido da Silva
logo: https://avatars3.githubusercontent.com/u/58571841?s=400&u=b7947c63cc25e1bf659ea402df5699898ea31ba1&v=4
description: [Linkedin](https://www.linkedin.com/in/gustavo-candido-da-silva-a90497a4/)
show_downloads: false
